disqus: ## Disqus评论系统，支持DisqusJS API
  enable: false ## If you want to use Disqus comment system, please set the value to true.
  shortname: ## Your disqus_shortname, e.g. username
  api: ## You can visit Disqus comments in China mainland without barriers using Disqus API, e.g. https://disqus.skk.moe/disqus/
  apikey: ## Your API key obtained in Disqus API Application, e.g. yk00ZB1fjYGRkrCrDDRYDUjpp26GJWJiJRZQZ5SY0r3th5FMW6pnSzQMnWH7ua7r
  admin: ## Username of your Disqus moderator, e.g. username
  admin_label: ## The text of Disqus moderator badge, e.g. Mod

uyan: ## 友言评论系统 Your uyan_id. e.g. 1234567
livere: ## 来必力评论系统 Your livere data-uid, e.g. MTAyMC8zMDAxOC78NTgz

changyan: ## 畅言评论系统 Your changyan appid, e.g. cyrALsXc8
changyan_conf: ## 畅言评论系统 Your changyan conf, e.g. prod_d8a508c2825ab57eeb43e7c69bba0e8b

gitalk: ## Gitalk评论系统相关参数 See: https://github.com/gitalk/gitalk
  enable: false ## If you want to use Gitment comment system please set the value to true.
  owner: ## Your GitHub ID, e.g. username
  repo: ## The repository to store your comments, make sure you're the repo's owner, e.g. gitalk.github.io
  client_id: ## GitHub client ID, e.g. 75752dafe7907a897619
  client_secret: ## GitHub client secret, e.g. ec2fb9054972c891289640354993b662f4cccc50
  admin: ## Github repo owner and collaborators, only these guys can initialize github issues.

valine: ## Valine评论系统相关参数 See: https://valine.js.org
  enable: false ## If you want to use Valine comment system, please set the value to true.
  appid: ## Your LeanCloud application App ID, e.g. pRBBL2JR4N7kLEGojrF0MsSs-gzGzoHsz
  appkey: ## Your LeanCloud application App Key, e.g. tjczHpDfhjYDSYddzymYK1JJ
  notify: false ## Mail notifier, see https://github.com/xCss/Valine/wiki/Valine-评论系统中的邮件提醒设置
  verify: false ## Validation code.
  placeholder: Just so so ## Comment box placeholders.
  avatar: "mm" ## Gravatar type, see https://github.com/xCss/Valine/wiki/avatar-setting-for-valine
  pageSize: 10 ## Number of comments per page.
  guest_info: nick,mail,link ## Attributes of reviewers.

minivaline: ## MiniValine评论系统相关参数 See: https://github.com/MiniValine/MiniValine
  enable: false ## If you want to use MiniValine comment system, please set the value to true.
  appId: ## Your LeanCloud application App ID, e.g. pRBBL2JR4N7kLEGojrF0MsSs-gzGzoHsz
  appKey: ## Your LeanCloud application App Key, e.g. tjczHpDfhjYDSYddzymYK1JJ
  placeholder: Write a Comment ## Comment box placeholder.
  adminEmailMd5: ## The MD5 of Admin Email to show Admin Flag.
  math: true ## Support MathJax.
  md: true ## Support Markdown.
  # MiniValine's display language depends on user's browser or system environment
  # If you want everyone visiting your site to see a uniform language, you can set a force language value
  # Available values: en  | zh-CN | (and many more)
  # More i18n info: https://github.com/MiniValine/minivaline-i18n
  lang:

utterances: ##  Utterances评论系统相关参数 See: https://utteranc.es
  enable: false ## If you want to use Utterances comment system, please set the value to true.
  repo: ## The repository utterances will connect to, e.g. tufu9441/comments
  identifier: title ## The mapping between blog posts and GitHub issues.
  theme: github-light ## Choose an Utterances theme which matches your blog.

twikoo: ## See: https://twikoo.js.org
  enable: false ## If you want to use twikoo comment system, please set the value to true.
  envId: ## Tencent CloudBase envId
  region: ## Tencent CloudBase region, e.g. ap-shanghai
  path: ## Article path, e.g. window.location.pathname

google_search: true ## 默认使用Google搜索引擎
baidu_search: false ## 若想使用百度搜索，将其设定为true

swiftype: ##  Swiftype 站内搜索keyYour swiftype_key, e.g. m7b11ZrsT8Me7gzApciT

self_search: false ## 基于jQuery的本地搜索引擎，需要安装hexo-generator-search插件使用。

google_analytics: ## Google Analytics 跟踪ID, e.g. UA-42425684-2
baidu_analytics: ## 百度统计 跟踪ID e.g. 8006843039519956000

fancybox: true ## 是否启用Fancybox图片灯箱效果

show_category_count: false ## 是否显示侧边栏分类数目

toc_number: true ## 是否显示文章中目录列表自动编号

shareto: false ## 是否使用分享按鈕，需要安装hexo-helper-qrcode插件使用

busuanzi: false ## 是否使用不蒜子页面访问计数

wordcount: false ## 是否使用hexo-wordcount文章字数统计

widgets_on_small_screens: false ## 是否在移动设备屏幕底部显示侧边栏

canvas_nest: ## 是否使用canvas_nest.js动态背景
  enable: false ## If you want to use dynamic background please set the value to true, you can also fill the following parameters to customize the dynamic effect, or just leave them blank to keep the default effect.
  color: ## RGB value of the color, e.g. "100,99,98"
  opacity: ## Transparency of lines, e.g. "0.7"
  zIndex: ## The z-index property of the background, e.g. "-1"
  count: ## Quantity of lines, e.g. "150"

donate: ## 是否启用捐赠按钮
  enable: false ## If you want to display the donate button after each post, please set the value to true and fill the following items on your need. You can also enable donate button in a page by adding a "donate: true" item to the front-matter.
  github: ## GitHub URL, e.g. https://github.com/Kaiyuan/donate-page
  alipay_qr: ## Path of Alipay QRcode image, e.g. /img/AliPayQR.png
  wechat_qr: ## Path of Wechat QRcode image, e.g. /img/WeChatQR.png
  btc_qr: ## Path of Bitcoin QRcode image, e.g. /img/BTCQR.png
  btc_key: ## Bitcoin key, e.g. 1KuK5eK2BLsqpsFVXXSBG5wbSAwZVadt6L
  paypal_url: ## Paypal URL, e.g. https://www.paypal.me/tufu9441

post_copyright: ## 是否在每篇文章后显示版权信息
  enable: false ## If you want to display the copyright info after each post, please set the value to true and fill the following items on your need.
  author: ## Your author name, e.g. tufu9441
  copyright_text: ## Your copyright text, e.g. The author owns the copyright, please indicate the source reproduced.

love: false ## 是否在任意点击处出现桃心

plantuml: ## 是否使用PlantUML生成UML图表 (https://github.com/miao1007/hexo-filter-plantuml).
  render: "PlantUMLServer" ## Local or PlantUMLServer.
  outputFormat: "svg" ## Common options: svg/png

copycode: true ## 是否为代码块启用一键复制功能

dark: false ## 是否使用深色模式主题

totop: true ## 是否使用返回顶部小火箭图标

external_css: false ## 是否加载外部CSS文件

menu: ## 自定义页面及菜单，依照已有格式填写。填写后请在source目录下建立相应名称的文件夹，并包含index.md文件，以正确显示页面。导航菜单中集成了FontAwesome图标字体，可以在这里选择新的图标，并按照相关说明使用。
  - page: home
    directory: .
    icon: fa-home
  - page: archive
    directory: archives/
    icon: fa-archive
  - page: about
    directory: about/
    icon: fa-user
  # - page: rss
  #   directory: atom.xml
  #   icon: fa-rss

widgets: ## 选择和排列希望使用的侧边栏小工具。 Six widgets in sidebar provided: search, category, tag, recent_posts, recent_comments and links.
  - search
  - tag
  - recent_posts
  - links
  # - category
  # - recent_comments

links: ## 友情链接，请依照格式填写。
  - title: hexo-author
    url: https://www.haomwei.com/
  - title: bigface
    url: https://www.doodo.cn/

timeline: ## 网站历史时间线，在页面front-matter中设置layout: timeline可显示。
  # - num: 1
  #   word: 2014/06/12-Start
  # - num: 2
  #   word: 2014/11/29-XXX

#  静态文件存储路径，方便设置CDN缓存 Static files 
js: js
css: css

# 主题版本，便于静态文件更新后刷新CDN缓存 Theme version
version: 1.0.0
